Entrega deber Julieth Gutierrez
LeninGF/CursoOverleaf pull request #8
Opened 2020-04-14 14:55 UTC by JuliethGutierrez1302

Gracias por su tiempo.

2020-04-14 15:23 UTC, LeninGF commented on deber/TeoremaMaestro.tex
> +
No le veo que le hayas removido a \title pero entiendo que la decisión pudo ser por hacerlo parecido al documento de wikipedia

2020-04-14 16:31 UTC, LeninGF commented on deber/TeoremaMaestro.tex
> +\vspace{1mm}
Esta parte deberías hacerla con algún código o paquete para algoritmos. Observa el siguiente ejemplo:
\usepackage[ruled,vlined]{algorithm2e}

EN el documento:
\begin{algorithm}[htbp]
\SetAlgoLined
\SetKw{exit}{exit}
\SetKwProg{Fn}{Procedimiento}{:}{end}
\Fn{T(n: tamañoProblema)}{
        \If(){
            $n<1$}{exit\;}
        \Else(){
            \Repeat{$a$ veces}{$T\left(n/b\right)$\;}
        }

    }

2020-04-14 16:41 UTC, LeninGF commented on deber/TeoremaMaestro.tex
> +\par \hspace{3mm} $T(n)=aT(\frac{n}{b})+f(n)$ donde $a \geq 1, b>1$\\
En una expresión matemática se pueden introducir espacios: https://pt.overleaf.com/learn/latex/Spacing_in_math_mode
Y los paréntesis se pueden poner del tamaño del objeto de la siguiente manera:
$T(n)=aT\left(\frac{n}{b}\right)+f(n) \quad \textrm{donde} \quad a \geq 1,\; b>1$

2020-04-14 16:42 UTC, LeninGF requested changes
Excelente trabajo, estan realizadas unas observaciones menores

2020-04-14 16:46 UTC, LeninGF requested changes
Exceletne trabajo

2020-04-14 16:46 UTC, LeninGF commented on deber/TeoremaMaestro.tex
> +\begin{itemize}
Simplemente llama a las referencias en el comando de bibliiografia no es recomendable usar itemize para las referencias.

2020-04-14 23:52 UTC, LeninGF commented
Hola las observaciones estan en forma de comentarios, me confirma si las puede revisar

2020-04-14 23:52 UTC, closed without merging

2020-04-15 02:45 UTC, JuliethGutierrez1302 commented on deber/TeoremaMaestro.tex
> +
Vale, muchas gracias...